### ISSUE TITLE
Suspicious assets: "fake Moneygram Token"Redirecting to real token.

### ISSUE THREAD

**Issue by stellarwatchdog** [Lobstrco/fraudulent-assets#103]
### Specific asset code(s) and issuer(s)
MONEYGRAM
Issuer:

GBPFUPZ2V24ZEGCYP7WUQSOKT74HJXY5RVVKC3OI5BYRP64RPD6NSHOT

### The reason why you think we need to blacklist these assets
Fake Moneygram token. Redirecting to real moneygram token. 

### Specific domain(s) of asset

https://moneygram.tomihosting.co

they are using a capital i instead of a L and redirecting to the real moneygram token

**Comment by CryptoHobbyist** [comment]
What is the  domain extention? .com  .co  .io  etc.

**Comment by CryptoHobbyist** [comment]
Do you know what the stellar address is?

**Comment by stellarwatchdog** [comment]
it’s .co

**Comment by stellarwatchdog** [comment]
> Do you know what the stellar address is?

GBPFUPZ2V24ZEGCYP7WUQSOKT74HJXY5RVVKC3OI5BYRP64RPD6NSHOT

**Comment by star-dust-one** [comment]
Thanks! The domain was added to our blacklist.
