### ISSUE TITLE
Suspicious assets: "FAKE CHEVRON TOKENS"

### ISSUE THREAD

**Issue by stellarwatchdog** [Lobstrco/fraudulent-assets#104]
More fake Chevron tokens same person using different domain name but now same issuer address different domain

### Specific asset code(s) and issuer(s)

CHEVRON (using stellarusa.vip now)
GAKRSCYI36DT5R6C4CRB5EGAGBWR3VNFM57NKDUI7HDKMA7BLX5QQUSA

CHEVRON (using stellarusa.org)
GCIYYWUVR74UIK6OS5GNGQR64YEIPE4GUNDDK3CCD5P3H2WT4WXQQ4JQ

CHEVRON (using stellar-usa.com)
GBUSOFG4NNWK37A6MB53K57LAWRKE35A3WNEJOSTHZRGLBOIVJXQ7USA

### The reason why you think we need to blacklist these assets
FAKE CHEVRON TOKENS

### Specific domain(s) of asset
stellarusa.vip
stellarusa.org
stellar-usa.com

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
![A3CB9673-607F-45DA-8EE5-CC66AB596D07](https://user-images.githubusercontent.com/108224279/180110860-be108967-5704-44b5-9b6d-786482cc9209.jpeg)

**Comment by star-dust-one** [comment]
Thank you! We added these domains to out blacklist.
