### ISSUE TITLE
Suspicious assets: "fake Moneygram tokens"

### ISSUE THREAD

**Issue by stellarwatchdog** [Lobstrco/fraudulent-assets#105]
These assets are using copyrighted and trademarked information including logos. And redirecting to the real moneygram website. 

### Specific asset code(s) and issuer(s)
MONEYGRAM - GCRWOZ7ODSTKQTSXJ5A4VAODFAPFGJOJT3KFZBTUMJGXQQKDGQFOSHOT

MONEYGRAM- GDXRJS2DALMIIZISB76563OE6BIFFFZZOBPLEMVAGNFZTAQ7NL33GRAM

MONEYGRAM-
GA6BRMYV6HI7ERJ7MDDNK7XAMCWYZAZNSYK3FXC2LM6OK7RXX735GRAM

MONEYGRAM-
GBPFUPZ2V24ZEGCYP7WUQSOKT74HJXY5RVVKC3OI5BYRP64RPD6NSHOT

### The reason why you think we need to blacklist these assets
Fake Moneygram tokens.

### Specific domain(s) of asset
moneygram-tomlhosting.com
moneygram-usdc.org
moneygram-stellar.org
moneygram-tomihosting.co

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
![5C03970C-F6A2-4513-8F2E-7ADFFDC2EB2D](https://user-images.githubusercontent.com/108224279/180281537-a733bbc6-b1c4-4989-8910-669e15751b33.jpeg)

**Comment by star-dust-one** [comment]
Thanks! These domains were added to the blacklist.
