### ISSUE TITLE
SCAM DOMAIN

### ISSUE THREAD

**Issue by samzacharry** [Lobstrco/fraudulent-assets#106]
Majority are duplicate of newly blacklisted whiplash domain. This entity follow whiplash to replicate his token.

### Specific Domain(s)
verified-assets.com
stronghoid.co
quantummetais.com
symgenta.tech
moneygram.tomihosting.co
stellarcannacoin.org
galileomiming.fund
elonstellar.co
e-russ.com
proiectguardian.digital
project-jura.com
stellarium.tech
stellar5xlm.com
stellarx5.com
steilarx5.com
xstellar.claims
lumensly.com
lobstr.claims

### The reason why you think we need to blacklist these domains
Scam Asset

**Comment by star-dust-one** [comment]
Thanks! We added these domains to our blacklist.

**Comment by Spxc** [comment]
Hi,
This is not correct as Stellar Cannacoin is NOT a scam asset.
