### ISSUE TITLE
SCAM DOMAIN (WHIP RELATED)

### ISSUE THREAD

**Issue by samzacharry** [Lobstrco/fraudulent-assets#109]
This entity follow whiplash to replicate his token.

### Specific Domain(s)
- space-indus.exchange
- spacetech.exchange
- tool-token.tech

### The reason why you think we need to blacklist these domains
Scam Assets

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
Whiplash

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
Whiplash

**Comment by CryptoHobbyist** [comment]
Less than two weeks left (Aug 31) for the "One Proof Challenge". 

In September there will be an open drawing to choose some of the victims reported on Rocky News to be the recipients of the amount raised for this challenge. Please consider donating to the  "One Proof Challenge" during these last days to show the victims the love we have in the community. 

100% of the XLM in the One-Proof-Challenge wallet, will be transferred to a winner of the challenge (no one has submitted proof all summer) or given to some victims (sadly only a fraction of those who have been scammed). https://t.me/OneProofChallenge

GBTB6H4TYEURXIK6INX7UHGAI7ZGH3VNSQIYBBCGMVYWFVQK4LQEKJDH

The win pool can grow by donation.

**Comment by star-dust-one** [comment]
Thanks! Added to the blacklist.
