### ISSUE TITLE
Replicator Of Already Blacklisted Fraudulent AssetList Contain 10% Scam Asset On Stellar

### ISSUE THREAD

**Issue by samzacharry** [Lobstrco/fraudulent-assets#11]
* moneygramtomlhosting.co
* stellargram.org
* Pendullum.pw
* Pendulun.pw
* stella-russia.io
* russiaindus.exchange
* hi-technetwork.org
* tech.lndus.org
* lndus.org
* deluxe-indus.exchange
* chemitokens.com
* digital-indus.exchange
* stellarflare.org
* stelarmart.org
* cbdctokens.net
* eurb.digital
* itautilitiess.co
* ita-utilities.com
* itautilities.co
* krungsri-finance.org
* indus-network.org
* cdbc-tokens.org
* cbdc-stellar.org
* quantum-space.org
* blackbox-exchange.org
* dz-bank.capital
* dzbanks.capital
* dz-bank.net
* vebrf-digital.com
* vebrf.capital
* verbfdigital.co
* ctgx-stellarmint.io
* ctgx-stellarmlnt.io
* ctgx-stellarmint.com
* ctgx-stellarmint.net
* indus-gold.org
* induspay.gold
* stellar-indus.exchange
* indusken.org
* tomlhosting.co
* swisscustody-gold.com
* russia.usdn.tech
* metalsstellar.com
* stellar-metal-initiative.com
* stellar-metals.com
* sungold.gold
* stellarcustody.gold
* induspay.gold
* imdus.gold
* binance.srl
* raretokens.org
* turkey-stellar.com
* turkeystellar.com
* turkey-stellar.org
* flare-network.io
* lumensstore.com
* stellarcenter.io
* trust-coin.net
* stellar-exchange.com
* xstellar.so
* flarenetworks.co
* swiss-custody.com
* afreum.net
* stellar-funds.co
* stellarfunds.exchange
* digitalfinance.stellarmint.io
* stellarhedgefunds.com
* stellarmart.com
* getmetacoin.org
* stellar-market.org
* social-truth.net
* strong-hold.co
* stellardevelopers.dev
* eastellar.com
* iso20022.finance
* expertstellar.com
* stellarmarketcap.com
* centerstellar.com
* stellarstudio.online
* kucoin.trade
* netlify.app
* stablestellar.com
* publicstellar.com
* stellarcenter.org
* social-truth.co
* gesarateam.com
*

**Comment by MoneyGT** [comment]
You have ever domain listed except yours. Beware Scammer.

**Comment by star-dust-one** [comment]
Thanks! The majority of these domains were added to our blacklist.
