### ISSUE TITLE
FAST! - !!! SCAM DOMAINS REPORT !!!

### ISSUE THREAD

**Issue by quadrigaex** [Lobstrco/fraudulent-assets#115]
### Specific Domain(s)
-
rippie.claims
lso20022coins.com
xdc-co.org
quantum-finance-network.org
biackbox.exchange
brics-network.org
indus-gold.finance
stellarassets.claims
indusx.exchange
iso20022.exchange
xrpflare-network.org
flare-assets.com
iso2oo22.org
xdcc0.org
xdcco.org
projectxdc.digital
binance-stellar.exchange
stellarxlm.org
quantum-finance-system.org

### The reason why you think we need to blacklist these domains
-
scam asset / whiplash / copyminter!

**Comment by star-dust-one** [comment]
Thanks! All assets were added to our blacklist.
