### ISSUE TITLE
Suspicious domains: <domain name>

### ISSUE THREAD

**Issue by charmeine** [Lobstrco/fraudulent-assets#14]
It s some copycats of already blacklisted websites and I think u forgot or maybe you don  t know about them

### Specific Domain(s)
stellarasset.co 
quantumstellar.tech/
stellar-go.com
strongholdtesla.org
stocks-on-stellar.org

### The reason why you think we need to blacklist these domains
All of them are copy-cats of othder domains that were blacklisted

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
I bought some tokens from all of these websites. From them and from the copy-cats that were blacklisted.

Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
All of domains have issuers with fraudulent activity alert on stellar.expert. All of them have it.

**Comment by star-dust-one** [comment]
Thanks. All domains were added to our blacklist.
