### ISSUE TITLE
Suspicious domains: "domain name"

### ISSUE THREAD

**Issue by charmeine** [Lobstrco/fraudulent-assets#15]
You can see yourself they are scams domains with moneygram token, they try to stole people xlm buying fake moneygram/usdc

### Specific Domain(s)
moneygram.tomlhostlng.co
moneygram.tomlhosting.io
stellar-moneygram.com
blackbox-exchange.org
moneygram.stellarteam.io
stellarflare.org
uniquestellar.org
masterstellar.com
stellarchips.com
deluxe-indus.exchange

### The reason why you think we need to blacklist these domains
They have created moneygram token

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
They have created moneygram token

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
They have created moneygram token

**Comment by star-dust-one** [comment]
Thanks. All domains were added to our blacklist.
