### ISSUE TITLE
Suspicious domains: "domain name"

### ISSUE THREAD

**Issue by samzacharry** [Lobstrco/fraudulent-assets#17]
These are copycat of already blacklisted domains. and they are still scamming people. please do something about this

### Specific Domain(s)
- imdus.gold
- induspay.gold
- stellarcustody.gold
- sungold.gold
- swisscustody-gold.com
- ctgx-stellarmint.io
- indus-gold.org
- induspay.gold
- stellar-indus.exchange
- indus-network.org
- digital-indus.exchange
- deluxe-indus.exchange
- Lndus.org
- stella-russia.io
- russiaindus.exchange

### The reason why you think we need to blacklist these domains
All of them are copy-cats of other domains that were blacklisted

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
Whiplash and QSI

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
Whiplash and QSI

**Comment by star-dust-one** [comment]
Thanks. All domains were added to our blacklist.
