### ISSUE TITLE
Suspicious domains: "domain name" Pendulum Scam TOKEN

### ISSUE THREAD

**Issue by samzacharry** [Lobstrco/fraudulent-assets#18]
They claim to be the real pendulum by selling fake pendulum asset

### Specific Domain(s)
- Pendullum.pw
- Pendulun.pw

**Edit** 
Both of the above domain were purposely brought down by the issuer below are the issuer addresses 
- Pendullum.pw **GBBIIQAP7H6H5WIGUUFTAHJMH7FDHYAEYQN2F2XUUWN5BCTYOYAPPEND**
- Pendulun.pw  **GDNWL7NQF7ASEHPV6YTTFHWJB4V4VINZG5M5PUSGQVAZNB6Q2P7MPEND**

### The reason why you think we need to blacklist these domains
THEY ARE SELLING FAKE PENDULUM ASSET

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
WHIPLASH AND QSI

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
WHIPLASH AND QSI

**Comment by djolehaubica** [comment]
ABOVE STATEMENT IS A COMPLETE LIE & FAKE. 
THEY ARE ALL  KNOWN CRIMINALS, PUSHING THIS FAKE NARATIVE AGAINST WHIPLASH AND QSI. 
THEMSELVFES ARE PUSHING  FAKE TOKENS ON MULTIPLE WEBSITES, WHILE DRAINING LIQUIDITY ...

DOMAINS THAT ARE FAKE ARE: 

donttread.stellarmint.io
kingtroll.stellarmint.io
kabbalah.stellarmint.io
geekmom.stellarmint.io
jobs.xmint.io
