### ISSUE TITLE
Suspicious domains: "domain name"

### ISSUE THREAD

**Issue by charmeine** [Lobstrco/fraudulent-assets#24]
lobstrr.co

### Specific Domain(s)
lobstrr.co

### The reason why you think we need to blacklist these domains
lobstrr.co

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
lobstrr.co

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
you also can see is a scam domain

**Comment by star-dust-one** [comment]
Thanks. All domains were added to our blacklist.
