### ISSUE TITLE
Suspicious domains: "domain name" GOLD TOKEN SCAM

### ISSUE THREAD

**Issue by samzacharry** [Lobstrco/fraudulent-assets#49]
### Specific Domain(s)
- metalsstellar.com
- stellar-metals.com

### The reason why you think we need to blacklist these domains
Deauthorization of asset holders after they make purchase of the token.. This issuer has deauthorize more than 5000 trustline..
I got tired counting you can check yourself. This is another act performed by the same entity

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
Whiplash

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
Below are pictures that show the act. Blockchain never lie

**Comment by mikeaol** [comment]
stellar-gold.org also a scam

**Comment by samzacharry** [comment]
Please feel free to add domain i missed

**Comment by mikeaol** [comment]
metals-on-stellar.org

**Comment by MoneyGT** [comment]
Cincinnati, Ohio

**Comment by samzacharry** [comment]
> Imagine u tried to block everybody assets on lobstr and u got blacklisted and now u r frustrated

what i don't seem to understand is we know you probably created a scam token but while Deauthorize asset holder after they make purchase of your token. This is the part i don't seem to understand. I'll say this is Pure Evil.
