### ISSUE TITLE
Suspicious domains: "domain name" MoneyGram Token Scam

### ISSUE THREAD

**Issue by samzacharry** [Lobstrco/fraudulent-assets#50]
I don't know why this domain has not been brought down yet but it seem the issuer has a tactic of hiding his domain. Am going to provide you with the issuer address so you can track this entity
Moneygramtomlhosting.co [GBY25WETKGV6IR7EX6WY5QUTDSWWUXOHSHFIJDC2T3BTAW63FKQRSHOT]

### Specific Domain(s)
Moneygramtomlhosting.co

### The reason why you think we need to blacklist these domains
They created a fake moneygram token for scamming

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
It listed Above

**Comment by samzacharry** [comment]
![image](https://user-images.githubusercontent.com/106759886/173792398-9b3a1fda-b319-43d7-a39e-b2545c112cc0.png)

**Comment by MoneyGT** [comment]
Yes this is the fake moneygram token. The real one is at moneygram.tomlhosting.co

**Comment by star-dust-one** [comment]
moneygram.tomlhosting.co and moneygramtomlhosting.co were added to our blacklist. Thanks.

**Comment by MoneyGT** [comment]
> moneygram.tomlhosting.co and moneygramtomlhosting.co were added to our blacklist. Thanks.
moneygram.tomlhosting.co Should not be on the black list it’s not a scam token and it discloses in their description not affiliated with moneygram. They have their own logo and the issuer account is locked.
