### ISSUE TITLE
Suspicious domains: "domain names"

### ISSUE THREAD

**Issue by quadrigaex** [Lobstrco/fraudulent-assets#54]
Majority are duplicate of newly blacklisted whiplash domain. This entity follow whiplash to replicate his token.

### Specific Domain(s)
tempocrypto.org
swiss-custody.org
stellarussia.com
stellarusd.digital
stellartokens.network
stellar-lumens.network
stellarhedgefunds.org
shxglobalpayment.com
metaversestellar.com
dogelonasset.com
cyber-technologies.org
astrosstellar.org
agrogenesis.bond
galactic-doge.com
etxco.co
itautilities.co
oceantokens.co
shiba-killer.io
stocksstellar.org
turklsh-gems.org
turkishgems.org
russian-asset.digital
ddex.capital
lumensswap.com
belarus-asset.digital
stablestellar.org
ixinium.co
stellarflare.xyz

### The reason why you think we need to blacklist these domains
Fake Token

**Comment by star-dust-one** [comment]
Thnks. All domains were added to our blacklist.
