### ISSUE TITLE
Suspicious assets: "ALGO, BabyXLM, CSC, GALA, interledger, SGB, Songbird, WSGB, XDC, XinFin, XRP"

### ISSUE THREAD

**Issue by quadrigaex** [Lobstrco/fraudulent-assets#55]
### Specific asset code(s) and issuer(s)
Asset CODE : ALGO, BabyXLM, CSC, GALA, interledger, SGB, Songbird, WSGB, XDC, XinFin, XRP
Domain: https://stellarflare.xyz
Issuer : GAXENTSWB4O6LSQSHPXMGZ7SBJYHLOGQZ25HMCKLF4X5G7ZNYZB62FLR

### The reason why you think we need to blacklist these assets
I'm pretty sure this is a scam tokens and that issuerID and domain should be lock.

### Specific domain(s) of asset
http://stellarflare.xyz/

**Comment by star-dust-one** [comment]
Thanks. This domain was added to our blacklist.
