### ISSUE TITLE
Suspicious domains: "4 domain names"

### ISSUE THREAD

**Issue by quadrigaex** [Lobstrco/fraudulent-assets#57]
Majority are duplicate of newly blacklisted whiplash domain. This entity follow whiplash to replicate his token.

Specific Domain(s)
flarestellar.xyz
stablestellar.org
shiba-killer.io
galactic-doge.com

The reason why you think we need to blacklist these domains
Fake Token

**Comment by star-dust-one** [comment]
Thanks. Domains were added to our blacklist.
