### ISSUE TITLE
Suspicious domains: "domain name" - List of Whiplash scam domains/tokens

### ISSUE THREAD

**Issue by Balmound** [Lobstrco/fraudulent-assets#58]
List of Whiplash scam tokens, all promoted on his Telegram Group that aren't blacklisted yet.

### Specific Domain(s) not Blacklisted yet

chinaresources.io
ubsinnovations.capital
cb-bitnickel.co
Quantum-future.co
Tascombank.exchange
Bitt.exchange
Vdcs.io
Mobius.network
Ixinium.io
Dsq.technology
CryptoRussians.Ru
Bitt.exchange
Pendulumbank.pw
Xlminr.com

### The reason why you think we need to blacklist these domains
Me with quadrigaex  and samzacharry decided to report all scams domains. Fake tokens with copy cat domains just for scams.

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
Whiplash Telegram promoted but not blacklisted or reported yet.
![Screenshot_16](https://user-images.githubusercontent.com/78938493/173955516-ca09774f-db33-4f2f-988b-c6f194d46da3.png)

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
Whiplash Telegram

**Comment by CryptoHobbyist** [comment]
> Quantum-future.co

Please feel free to help with my list. It is now unfortunately over 500.
https://docs.google.com/spreadsheets/d/1JCkWZ3X1h6kJKM6ZCZThDshK_whhNiTyGTV8R24Anho/edit?usp=sharing

**Comment by star-dust-one** [comment]
Thanks for your helpful data. Some domains were added to our blacklist.
