### ISSUE TITLE
Suspicious assets: "asset name" : Lobstrr.co (double r) Active Scams after blacklist. Issuer Scams

### ISSUE THREAD

**Issue by Balmound** [Lobstrco/fraudulent-assets#59]
### Specific asset code(s) and issuer(s)

lobstrr.co

Issuer : GDWKS7O7RQY4ZRHPHLLMP63CGGNWCK72MP5J6FMVANA45ZI5WBJLQFHN

### The reason why you think we need to blacklist these assets

All assets issued by this Issuer are fake tokens, more then that it claims to be ''Lobstr''

### Specific domain(s) of asset

lobstrr.co

### The source where suspicious assets are mentioned (e.g. Telegram/WhatsApp/Facebook links)
StellarMart (New telegram group made and promoted by Whiplash347 guess for what? exacly scams.

![Screenshot_18](https://user-images.githubusercontent.com/78938493/173956395-a169021f-797c-4ecb-ab99-bb2a930ec729.png)

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
![Screenshot_17](https://user-images.githubusercontent.com/78938493/173956329-20cd413b-b268-4a1a-958f-b2e2f9d2f914.png)

**Comment by samzacharry** [comment]
why do you keep changing your username??.. are you trying to have different Personalities here??

**Comment by samzacharry** [comment]
this is the fourth time you are changing yours username?? yesterday i could swear you were “doncristi”

**Comment by star-dust-one** [comment]
Thanks. This domain was added to our blacklist.
