### ISSUE TITLE
Whiplash347 Distributors and Scam Domains

### ISSUE THREAD

**Issue by robertolazarus82** [Lobstrco/fraudulent-assets#60]
Hello after few hours of searchin on stellar.expert i found all his domains and i figured those are his distribuitors cuz all of them had payments between them and all of them are connected. U can also check all of them via payment locator on stellar expert and it s easy.

"GAWFKL7J46QRPQNTRDC7OI433CLCXHWMZ5SWFDOW25S7ONEMOJYFLARE",
"GB2OCHBCGWB4O5MBLO3AWANQUYSIPQ4DKEOAAAZK72GG2L74RCZNPZD4",
"GDYUE6OZMD2QDHT4NLJUFGLJ7AOUTQLT36IXKJIIF3FNCHHWLIUHLQFS",
"GANLVXOAJVOEESG7HC4AQYEOQNUU2M2TMWXP3VMAOVR7W7HS7YYTUA55",
"GC23ZKFWW2D5MAYOHJVZKV5PN5QCCRAP5OCLYENVBMHHHWNHS74R7PE5",
"GDHSW3BOZJDGM5CYPERKVNNVI4M57OLANPXZZSBUZNKBN6DUKB5DJS7M",
"GDV5P2H2ZUF64OWPTNXEFOO2FWUWPWX7SVESYEDT7CYXBYJ4O3ZQDI6U",
"GD7JZSTABKLHS5PDX6LQGBH5IKZ3GOLTCDQTOVMW2SHIDGTNFLPWHQFS",
"GAI26JX52M6H3POC2P4LJRDZ7NC7G3KMIQTITIGCBFHOPHCOWUZTRUMP",
"GDU77WI2AU7DUK42EMS7EINJ747SSAGAGN56ZRR5AYD33WIXWC6RO3LP",
"GCDFIBPHGXLU6JWZYKMX6KB4BE5NKJEP4FOFNWHXMNVKYSS4KNUSWISS",
"GBZ2EL4ES2JQ6DEH7PHBFLMNLRJJOGIDOJMQCYMF5OPNOH7VDXWLLQFS",
"GDO2XR443CJHHOFIFGWBLOOY3TFDEHHXVV5HHPNHAFWXX3DMPPVTDEYY",
"GBYREQTJKAOBPEXC3YGUE3IV3DVGNAO27QRB7BALTIUQBEWBBHYKYTNY",
"GCPBVHEW6PPP5MAGF5TCQSFEKXBF2JMCQWG2SH6UXMTT7J2HLWNM3FAI",
"GA7KUU6AM4ZDNM46HNMDFT6OKEJQ6RSWTFP2CM34QLVGYOFCJ52NCRB7",
"GCU4V4T5EDLVM56EVB3DKMVPMLPUOFRDWFC2OE4D7KF23WHD2ATZMWKY",
"GB2TPJA7D6J6N4VIRMSL4UXKRNSLRMORJNW6S3A7MO7F6IGEPK6N7CXL",
"GAUNEK6KTXRISSGODYFMG6KT4WRUBNMSSFOYSD2U27G2T5UX32IE4KR3",
"GAVGBMQRCCRJLCEP46CZRGN3HWDYS7IBSNPUSSUZVKTWQVP7L3KQN4XW",
"GDMX6CIB2UCMEIBLIDKDJQUVN3SDYLVD354V6WO5WRHWLGTHZUJ4SIXK",
"GCPYA2KM2IO4KFQEMDV2K6SEBWGETLVGK7XEFXGTFJQNKQAYBMQ7KIMZ",
"GD5UP4R7J26XSANLYXQ5DERHDPYYOORVJUPMTTXSM7RLLDJHRLRUGK7C",
"GBH2EQFS67EIFGZDO5AEIEL6FZKB7YVUEEU3LXCCRDK6AQCPJ5MOARK3",
"GDYE5QBWUKN3ZKDY3R3YX3LE3HXBQ72T4SFL5RD2IKOR7HHX2E4DZJ2V",
"GDJMUWQT2YFGYDF2XYVPL242U5F7YMBNEHYKVDJ7EDSW4R2KR2CY6WYJ",
"GC5466K2YLBHTY7YSAZF53WS5HF7M2WRIUCY5JWKU5Q3DWXXOVTCBBOX"

All of these distribuitors has a total balance of 9 milions xlm
All of those below domains were collected from upper distribuitors, i started serachin indus scam domains, flare networks and other replicator website of what whiplash promotes.
Majority of domains has l instead of i, "m" was changed to rn, t to f, he also added some S at the beggining or final of the domain, diffrent org net com io domains but same domain for example indusx.org indusx.net etc

Please check yourself all these distribuitors cuz all of them are connected via payment locator with 3000-1m XLM and how i said i collected all of them from this distribuitors, i m not sure if it s all domains collected but i tried to collect almost all.

### Specific Domain(s)
vebrfr.digital - veb.rf scam token this is a russian bank and it s whiplash replicator 
indus.bond - fake indus and replicator tokens
astrostellars.org - fake whiplash replicator and he added s at final to this domain
inter-stellar.exchange - fake interstellar website
interstellarx.exchange - fake interstellar website
infinity-gold.co - fake gold token
rare-tokens.org - fake xrp gold and other tokens
purestellar.org - fake companies tokens
strongholdpayx.co - fake stronghold website
strongholdpay.co - fake stronghold website
stellar-networks.co - fake xrp, gold, miota and LOBSTR token
stellar-metaverse.com - fake metaverse projects
StellarETFs.com - fake etfs stellar tokens
StellarRealEstate.org - fake companies tokens
cicada.xmint.io - fake cicada token
gov.stellarbonds.exchange - fake bonds tokens 
stellarbills.com - fake companies and other tokens like xrp shib etc
balancedstellar.com - fake companies tokens
StellarHedgeFunds.com - fake gold tokens
luxor.tomlhosting.co - fake tomlhosting replicator 
hjstoken.stellarmem.org - fake tokens
ripplenode.com - fake ripple tokenn
trust-coin.net - fake replicator of trusttoken
exchanges.indus.exchange - indus scam domain
digitalfinance.stellarmlnt.io - fake stellarmint replicator
quantum-tokens.org - fake quantum tokens
flare-network.exchange - fake flare domain
stocks-on-stellar.org - fake stocks domains
thecontinuum.ca - fake companies token
go-dls.com - fake companies token
thestellarfarm.com - fake stalking website with fake tokens
luxbank.co - fake lux bank token
stellarkraken.com - fake kraken replicator tokens
stellarmarketcap.com - fake xrp ada etc tokens
publicstellar.com - fake xrp shib ada and other companies tokens
bonesteel.io - fake companie tokens
iccol.co - fake teslacoils token
indusx.org - fake indus replicator
stellardogelon.com - fake dogelon token
stellar-square.com - fake companies tokens
stellardevelopers.org - fake companies tokens
stelar-flow.com - fake companies tokens
stellarhq.io - fake companies tokens
gold.indus.bond - fake indus tokens
quantumsystem.finance - fake quantum tokens
stellarasset.co - fake companies tokens
stellarverse.tech - fake companies tokens
Stellar-Mainnet.com - fake stellar issuer tokens
starbridge.host - fake starbridge token
splcytkn.org - fake spicy token 
stelar-fusion.com - fake xrp and other companies tokens
flare-finance.io - fake flare website
qfs-tokens.org - fake qfs tokens
pendullum.pw -fake pendulum tokens
StellarHQ.io - fake stellar tokens as xrp and also companies
hyperledger.lndus.exchange - fake indus tokens
algodex.trade - fake algodex exchange tokens
anchored-tokens.org - fake original tokens
metals-on-stellar.org - fake metals token as gold silver platinum etc
itautilities.stellarmlnt.io - fake stellarmint replicator
hyperledger.technology - fake hbar token
newstellar.io - fake companies tokens
wxt.wlrexapp.com - fake wirex app exchange
quantum-stellar-initiative.org - fake quantum tokens
continentalpublicsbank.com - fake banker coin token
pendullumbank.pw - fake pendulum token
www.oceanstokens.org - whiplash website
stellar-tesla.energy - fake tesla coin
ddex-digital.com - fake company token
ddexdigital.com - also other replicator token
hl-technetwork.com - fake domain he added l instead of hi
yaqua.network - fake aqua token
exemusexchange.stellarteam.org - fake tokens as xrp and companies token
stellarteam.io - other stellarteam domain
stellarteam.co - other stellar team fake domain
moneygram.stellarteam.io - fake moneygram token
meta.stellar.onl - fake stellar website
enaira.usdf.tech - fake usdt token
emergency-tokens.stellarteam.org - other stellarteam replicator
dlx.stellarteam.org - orther stellartem replicator
zodaictokens.org - zodiactokens replicator by whiplash
squidgame.stellar.onl - fake stellar website
trumpcoin.stellarmint.io - fake trumpcoin
assets-indus.exchange - fake indus tokens
turklsh-lira.org - fake turkish lira replicator 
indus.social - fake indus tokens and also replicator
stellarassets.net - fake tokens as tesla riiple labs etc
quantumstellar.ai -fake quantum tokens
flare-networks.ai - fake flare tokens
thefavens.org - fake company token
lndus.exchange - fake indus tokens
cyber-technoloqy.org - fake website replicator of whiplash
cbdc-token.org - fake cbdc bank tokens
stellar-network.co - fake xrp and company tokens
agriogenesis.in - promoted by whiplash
stellarassets.io - other replicator of stellarasset website
stocks-on-stellar.org - fake stocks tokens
stellar-gold.org - fake gold tokens
lumens.exchange - fake xrp xdc and other tokens
quanturn-system.finance - fake quantum tokens
chemitoken.org - fake chemi tokens replicator 
tomlhostlng.co- fake tomlhosting website
anon-inu.com - anoninu fake website
bitbox.exchange - fake xrp algo and other tokens
lcx.digital - fake banker coin
quantum-stellar-system.org -fake quantum tokens
realio.fund - i don t know if its real or not but i think it s also a scam token and he s the distrubitor
swisscustody.gold - swisscustody fake tokens and companies gold and other
swisscustody.induspayment.com - indus fake tokens
swisscustodys.org - other swisscustody fake replicator
turkish-lira.org - fake turkish lira website
digital.lndus.exchange - fake indus exchange
vebrf.lndus.exchange - fake veb.rf token
vebrfs.digital - fake veb.rf token
bpflnvest.fund - fake bank token
anclap.io - fake token
doa-digital-on-asset.com - fake bnaker coin
stellar-quantum.org - fake quantum tokens
astro-stellar.org - other astrostellar fake replicator
quantum-financial-system.org - fake quantum tokens
quantum.org - fake quantum tokens
z-finance-system.vercel.app - fake z finance token
cyber-technology.org - other cyber technology fake replicator
giga-doge.com - whiplash token
pendulums.pw - pendulum token
spicytkn.org - other spicy token replicator
quantuldollars.digital - quantum dolla fake token
thetopfunds.org - fake tokens as xrp 
pendulumsafe.pw - pendulum replicator
indusx.tech - indus replicator
inclus.gold - indus replicator
inclus.exchange - indus replicator
lndus.exchange - indus replicator
kazakhstan-indus.exchange - indus replicator
strongpaystellar.com - fake shx token
thefarsights.net - fake german tokens
astronauts.foundation - whiplash replicator
ultra-stellar.org - fake ultrastellar domain
lndus.gold - indus replicator
indus.bond-  indus replicator
lndus.exchange - indus replicator

### The reason why you think we need to blacklist these domains
Scam and fake tokens, replicator of huge companies and whiplash replicator

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
just check what i said and blockchain doesnt lie

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
<img width="601" alt="9m" src="https://user-images.githubusercontent.com/107628224/174097378-61a14b62-38f8-4fea-b0a3-083b27e95452.png">

**Comment by CryptoHobbyist** [comment]
Thank you for your work. Please fell free to help with my recorded list of over 500 very questionable domains. 
https://docs.google.com/spreadsheets/d/1JCkWZ3X1h6kJKM6ZCZThDshK_whhNiTyGTV8R24Anho/edit?usp=sharing

**Comment by star-dust-one** [comment]
Thank you! All domains were added to our blacklist.
