### ISSUE TITLE
Suspicious domains: "domain name"

### ISSUE THREAD

**Issue by mikeaol** [Lobstrco/fraudulent-assets#61]
fake insterstellar domains, also fake gold token, and copycat of original tokens as xrp, btc, xdc 

### Specific Domain(s)
inter-stellar.exchange 
interstellarx.exchange 
infinity-gold.co 
stellar-gold.org 
lumens.exchange 
bitbox.exchange 

### The reason why you think we need to blacklist these domains
they issued scam tokens

**Comment by star-dust-one** [comment]
Thanks! All domains were added to our blacklist.
