### ISSUE TITLE
Suspicious domains: "domain name" USDC SCAM ASSET

### ISSUE THREAD

**Issue by samzacharry** [Lobstrco/fraudulent-assets#62]
This domain minted USDC fake token

### Specific Domain(s)
twistedstellar.com - Created a fake USDC token
hiddenstellar.org - Created a fake USDC token
galaxystellar.com - Created a fake USDC token
ultrastellar.fun - Created a fake USDC token
lumens-coin.com - Created a fake USDC token
stellarteam.tech - Created a fake USDC token
Easttellar.com - Created a fake USDC token
stelarport.io - Created a fake USDC token
stelarterm.com - Created a fake USDC token
stellarmarket.exchange - Created a fake USDC token
stellarliquidity.com - Created a fake USDC token
usdc.gold - Created a fake USDC token
stellar-team.org - Created a fake USDC token

### The reason why you think we need to blacklist these domains
They have created a fake USDC token

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
Listed Above

**Comment by CryptoHobbyist** [comment]
You had a lot of domains that had not already on my list of over 500 very questionable domains. Please feel free to contributing to this with any facts that you find.
https://docs.google.com/spreadsheets/d/1JCkWZ3X1h6kJKM6ZCZThDshK_whhNiTyGTV8R24Anho/edit?usp=sharing

**Comment by star-dust-one** [comment]
Thank you! All domains were added to our blacklist.
