### ISSUE TITLE
Domains to add

### ISSUE THREAD

**Issue by rilled** [Lobstrco/fraudulent-assets#7]
*.indusx.tech
*.pendulumbank.pw
*.astronaut.foundation
*.stellar-quantum.com
*.ultrastellar.com
*.bpfi.ie
*.astrostellar.org
*.cryptog.finance
*.ctgx.io
*.dsq.technology
*.dstoq.tech
*.dstoq.technology
*.astrowallet.org
*.luckystellar.com (hosting over 50 scam tokens: https://luckystellar.com/.well-known/stellar.toml)

*.pendulumsafe.pw and *.pendulum.pw are on the list currently, but are not flagged as fraudulent on the app anymore.

**Comment by djolehaubica** [comment]
you are not enough that you are lieing in Rocky and other chats but u come here with the same bullshit. give me break and get a life

**Comment by star-dust-one** [comment]
Your examples of a suspicious domain like *.ultrastellar.com, *.dsq.technology are unacceptable. 
Please, follow the new creating issue guideline and provide all necessary data to blacklist suspicious assets/domains.
