### ISSUE TITLE
Sign the petition to stop this scam tokens https://chng.it/GHk5v5Drch: SCAM TOKEN"ULTRASTELLAR.com"

### ISSUE THREAD

**Issue by ghost** [Lobstrco/fraudulent-assets#72]
### Specific Domain(s)
ULTRASTELLAR.COM

### The reason why you think we need to blacklist these domains

https://chng.it/GHk5v5Drch

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)

https://chng.it/GHk5v5Drch

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)

sign the petition to stop this scammer 
https://chng.it/GHk5v5Drch

**Comment by samzacharry** [comment]
worthless
