### ISSUE TITLE
Suspicious domains: "domain name" MIOTA SCAM ASSET

### ISSUE THREAD

**Issue by samzacharry** [Lobstrco/fraudulent-assets#74]
This domain minted fake MIOTA token

### Specific Domain(s)
xlmmiota.netlify.app - Created a fake MIOTA token
powerstellar.com - Created a fake MIOTA token
miota.netlify.app - Created a fake MIOTA token
stellarium.exchange - Created a fake MIOTA token
stellardex.exchange - Created a fake MIOTA token
stellarpay.trade - Created a fake MIOTA token
stellartokens.trade - Created a fake MIOTA token
cryptostellar.trade - Created a fake MIOTA token
stellarport.network - Created a fake MIOTA token
stellarlumens.trade - Created a fake MIOTA token
stellarcoins.trade - Created a fake MIOTA token
stellarmars.trade - Created a fake MIOTA token
stellargold.trade - Created a fake MIOTA token
stellarhold.trade - Created a fake MIOTA token
stellarium.trade - Created a fake MIOTA token
stellarmint.trade - Created a fake MIOTA token
uniquestellar.trade - Created a fake MIOTA token
interstellar.network - Created a fake MIOTA token
stellarmoon.trade - Created a fake MIOTA token
resonagrup.fund - Whiplash token replicator. Impersonating RESONA Bank.
stellar-exchange.com - Created a fake XRP token

### The reason why you think we need to blacklist these domains
They have created a fake MIOTA token

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
Screenshot Below
![image](https://user-images.githubusercontent.com/106759886/174395254-80905440-c913-424c-8434-ee0507987817.png)

![image](https://user-images.githubusercontent.com/106759886/174406925-8dc42acf-05d0-4a67-b07e-9528a4790817.png)

**Comment by star-dust-one** [comment]
Thanks! Some of these domains were added to our blacklist.
