### ISSUE TITLE
Suspicious domains: "domain name" Newly Promoted Whip Fake Asset

### ISSUE THREAD

**Issue by samzacharry** [Lobstrco/fraudulent-assets#75]
### Specific Domain(s)
resonaSgrup.fund - Newly Promoted Whip Fake Asset
gaLLLeomining.fund - Newly Promoted Whip Fake Asset
sLngaporecrypto.digital - Newly Promoted Whip Fake Asset
ubsinnovatLons.capital - Newly Promoted Whip Fake Asset
chinaresorces.co - Newly Promoted Whip Fake Asset
anclapofficial.net - Original anclap is api.anclap.com
steLLLargibraltar.org - Newly Promoted Whip Fake Asset
stelargibraltar.org - Newly Promoted Whip Fake Asset
stellargLbraltar.org - Newly Promoted Whip Fake Asset
stellarteam.tech - Newly Promoted Whip Fake Asset

### The reason why you think we need to blacklist these domains
Newly Promoted Whip Fake Asset

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
Whiplash

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
![image](https://user-images.githubusercontent.com/106759886/174446603-583b2538-4db8-48cd-ad19-c4161c44d499.png)
![image](https://user-images.githubusercontent.com/106759886/174446619-62a211e4-ff32-4073-ab1c-fa924f426291.png)
![image](https://user-images.githubusercontent.com/106759886/174446626-9960be6d-9a4d-4a57-99b3-bffae1c619ae.png)
![image](https://user-images.githubusercontent.com/106759886/174534225-b177a5f0-bd7e-4ca0-8f52-5925b36ca4f0.png)
![image](https://user-images.githubusercontent.com/106759886/174594025-25c35795-06f0-4c7a-b5c8-12295fd70964.png)

**Comment by CryptoHobbyist** [comment]
All entered thanks for the update

**Comment by star-dust-one** [comment]
Thanks! We've blocked all domains.

**Comment by CryptoHobbyist** [comment]
It is awesome to see Lobstr working to making the exchange safer. I feel comportable now suggesting Lobstr to new comers. 
Keep it up.
