### ISSUE TITLE
Suspicious domains: "domain name" Newly Promoted Whip Fake Asset

### ISSUE THREAD

**Issue by samzacharry** [Lobstrco/fraudulent-assets#77]
### Specific Domain(s)
gaLLiLeomining.fund - Newly Promoted Whip Fake Asset
stellargLbraLtar.org - Newly Promoted Whip Fake Asset [GCTALOZHY6EJXDZ2OIR74C7UFXDIQW7F5M62QKIDQTMLYLHHRT3JC767]
kazakhsteLLLar.org - Newly Promoted Whip Fake Asset
sgpmx.fund - Newly Promoted Whip Fake Asset
algo-dex.org - Newly Promoted Whip Fake Asset
chLnares.gold - Newly Promoted Whip Fake Asset
stellarmongolia.org - **NEWEST!!!** Promoted Whip Fake Asset
   You can blacklist this before they are even created
   -steLLLarmongolia.org 
   -stellarmongoLLa.org
   -stelarmongolia.org

### The reason why you think we need to blacklist these domains
Newly Promoted Whip Fake Asset

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
Whiplash

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
![image](https://user-images.githubusercontent.com/106759886/174801537-d29b447c-d157-4884-b980-07931026bf11.png)
![image](https://user-images.githubusercontent.com/106759886/174801560-5b2be650-4d14-4773-903f-4c900a257a06.png)
![image](https://user-images.githubusercontent.com/106759886/174801713-1ad028b4-34b5-48fc-80cf-1dcfb9a0d538.png)
![image](https://user-images.githubusercontent.com/106759886/174801782-3f0b55d5-59aa-47f8-b768-62593ce98f69.png)
![image](https://user-images.githubusercontent.com/106759886/174801818-a751c3fe-4537-4c97-9f40-6f9466abd010.png)
![image](https://user-images.githubusercontent.com/106759886/174801849-26c45439-14dc-4cff-a107-f5d9b5972730.png)
![image](https://user-images.githubusercontent.com/106759886/174801879-38463e43-ce37-46f9-a953-b7c6c747dff2.png)
![image](https://user-images.githubusercontent.com/106759886/174801920-3254f54b-d7e7-4806-8613-a8e1b0aaeef1.png)
![image](https://user-images.githubusercontent.com/106759886/174801953-44e687d1-83d9-49a2-91ca-77228fee8a18.png)

**Comment by CryptoHobbyist** [comment]
The last three already forward to the https://stellarmongolia.org/ scam page great catch
