### ISSUE TITLE
Suspicious 20 domains!

### ISSUE THREAD

**Issue by quadrigaex** [Lobstrco/fraudulent-assets#78]
### Specific Domain(s)
stellar-exchange.com
gwallet.tech
vdcs.digital
stellartron.netlify.app
chlnares.gold
x.istellar.co
stelllarmongolia.org
BitBox.Exchange
xrpvault.stellarmint.io
xrpxau.stellarmint.io
preciousxrp.stellarmint.io
stellarmongolla.org
Stellarflies.com
brazil-asset.com
Eastellar.com
brazll-assets.com
Stellareast.com
stellarquarry.com
quantumteam.io
stellartopmarket.com

### The reason why you think we need to blacklist these domains
Fake/Scam assets!

**Comment by star-dust-one** [comment]
Thank you! These domains were blacklisted.
