### ISSUE TITLE
Newly Promoted Whip Fake Asset

### ISSUE THREAD

**Issue by samzacharry** [Lobstrco/fraudulent-assets#80]
### Specific Domain(s)
- LNDUS.TECH  - Indus Scam -  For unknown reason this domain is still visible on lobstr.
- stellarmongoLLA.org - Newly Promoted Whip Fake Asset
- stelarmongolia.org - Newly Promoted Whip Fake Asset
- stellar-mongolia.org - Newly Promoted Whip Fake Asset
- brazili-assets.com - Newly Promoted Whip Fake Asset
- brasil-assets.com - Newly Promoted Whip Fake Asset
- brazLL-assets.com - Newly Promoted Whip Fake Asset
- sgxpm.fund - Newly Promoted Whip Fake Asset
- chLnares.gold - Newly Promoted Whip Fake 
- Asset - For unknown reason this domain is still visible on lobstr.
- utimatum.network - Newly Promoted Whip Fake
- newstellar.org - Newly Promoted Whip Fake

### The reason why you think we need to blacklist these domains
Newly Promoted Whip Fake Asset

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
Whiplash

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
![image](https://user-images.githubusercontent.com/106759886/175114065-fa47a6e4-3dff-4ab9-a658-888fe15f635f.png)
![image](https://user-images.githubusercontent.com/106759886/175114400-9821799f-d96a-4b45-b4cd-92a9c6fc920d.png)
![image](https://user-images.githubusercontent.com/106759886/175114852-b5deecfa-9391-4282-a669-55d51638c3f7.png)
![image](https://user-images.githubusercontent.com/106759886/175115320-dd5136fa-8f41-487d-8168-e2d80f929fda.png)
![image](https://user-images.githubusercontent.com/106759886/175115735-cb85696e-06c2-487b-b998-12dfabb7a19b.png)

**Comment by star-dust-one** [comment]
Thank you! We added all domains to our blacklist.
