### ISSUE TITLE
Suspicious 11 domains (still listed)!

### ISSUE THREAD

**Issue by quadrigaex** [Lobstrco/fraudulent-assets#81]
### Specific Domain(s)
BitBox.Exchange - still appear on lobstr list and if you click on this website there will be "Coming Soon"!
lndus.tech or lNDUS.tech
krungrsl.finance
cb-bitnlckel.co
Eastellar.com
steiiar-au.org
steliar-au.org
magicstellar.org
noobstellar.com
Powerstellar.com
xlmhbar.netlify.app

### The reason why you think we need to blacklist these domains
Scamming domains/assets!

**Comment by samzacharry** [comment]
it is Lndus.tech and not indus.tech

**Comment by star-dust-one** [comment]
Thanks! All domains were added to our blacklist.
