### ISSUE TITLE
Suspicious assets: "yUSDC"

### ISSUE THREAD

**Issue by antb123** [Lobstrco/fraudulent-assets#82]
### Specific asset code(s) and issuer(s)
yUSDC GBVMYJEPKCMCTW4B7XKI2YUG4ON2YAR7NMXJEFKEJJ2ILPDW73OAOXOU

### The reason why you think we need to blacklist these assets
trying to scam ultrastellar

### Specific domain(s) of asset
[ultrastellar.fun](https://stellar.expert/explorer/public/asset/yUSDC-GBVMYJEPKCMCTW4B7XKI2YUG4ON2YAR7NMXJEFKEJJ2ILPDW73OAOXOU) (

**Comment by samzacharry** [comment]
its already on the blacklist
