### ISSUE TITLE
Delisting request - driftxhub.com

### ISSUE THREAD

**Issue by StellarGee** [Lobstrco/fraudulent-assets#83]
The driftxhub.com is the hub of the project driftxchange, which has launched on Stellar via auction in December 2021. The webiste of the project is driftxchange.com and neither the project nor the team is involved in any fraudulent activities. The Lobstr support has not answered any of our requests to delist us and research groups such as Stellar Token and Liberty crypto syndicate group don`t see any reason why our project is on the list, as it`s not connected to any fraudulent behaviour. We have partnerships with many renowned and verified Stellar artists and projects. Being on that list and tagged as scam token not only harms the project, but our community and investors as well. Noone has communicated to the project why it was listed and who is in charge of this. Researchers don`t know either why it is listed, as it is not on any of their lists.

**Comment by samzacharry** [comment]
Driftxhub isnt a scam domain also realiotoken isnt too.

**Comment by doczol** [comment]
@star-dust-one @tomerweller @cloudy-d

**Comment by stellarwatchdog** [comment]
Scam token creator or creators have set up different stellar addresses and are making it impossible for you to sell your tokens. They are using auto bots like kelp to defraud you. 
The block chain does not lie. It goes deep into the block chain but trust me it’s all there.


![715F15F6-D373-4B12-BF29-017FD4E46BBF](https://user-images.githubusercontent.com/108224279/175818221-c7ca64bd-50f7-4a38-abbc-8d0ed43a70f3.jpeg)
![36057BF4-5AD4-4DDF-AE00-CA9599BCC3F3](https://user-images.githubusercontent.com/108224279/175818222-0dbed23d-351b-4fd1-8407-9c127eff0861.jpeg)
![3990A816-F9C8-40DB-9FD9-EED175E7555E](https://user-images.githubusercontent.com/108224279/175818223-4356967f-dd71-438f-a93b-f7ef35801ef2.jpeg)

**Comment by star-dust-one** [comment]
Thanks for the report. We delisted the domain driftxhub.com. Sorry for the inconvenience.
