### ISSUE TITLE
ATTENTION XDC SCAM ASSET

### ISSUE THREAD

**Issue by mikeaol** [Lobstrco/fraudulent-assets#87]
stellar.claims issued multiple xdc xrp and other tokens

### Specific Domain(s)
stellar.claims 

### The reason why you think we need to blacklist these domains
stellar.claims 

### The source where suspicious domains are mentioned (e.g. Telegram/WhatsApp/Facebook links)
stellar.claims 

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
stellar.claims

**Comment by star-dust-one** [comment]
Thanks! Domains were added to our blacklist.
