### ISSUE TITLE
Suspicious 16 domains.

### ISSUE THREAD

**Issue by quadrigaex** [Lobstrco/fraudulent-assets#89]
### Specific Domain(s)
iobstr.co
steiiaruzbekistan.org
steiiarazerbaijan.org
elonsteiiar.com
steliar-au.org
cb-bitnlckel.co
steiiarazerbaijan.com
kzgoidmining.org
shanghalcoop.org
tendaogoid.org
stellarazerbaijan.com
venezueiastellar.org
steiiar-au.org
krungrsl.finance
brazll-assets.com
brazil-asset.com

### The reason why you think we need to blacklist these domains
SCAMMING ASSETS/FAKE/WHIPLASH

**Comment by CryptoHobbyist** [comment]
I've finished checking and adding these to my list, sadly it is now over 700 researched and found to be very questionable domains.

**Comment by star-dust-one** [comment]
Thanks! We've added these domains to our blacklist.
