### ISSUE TITLE
Domains to add

### ISSUE THREAD

**Issue by sunshinekills** [Lobstrco/fraudulent-assets#9]
.kingtroll.stellarmint.io
*.geekmom.stellarmint.io
*.kabbalah.stellarmint.io 
*.miri777.litemint.store  
*.donttread.stellarmint.io
*.geekmom.litemint.store
*.na06y1.litemint.store

**Comment by CryptoHobbyist** [comment]
There is a difference between scam and useless

**Comment by munsayac13** [comment]
Project Seraphim, CryptoBrownie, Whiplash347 and QSI Channels in telegram will block you if you mention you are buying XRP.

**Comment by star-dust-one** [comment]
We haven't seen any suspicious activities from these domains. Please, follow the new creating issue guideline and provide all necessary data to blacklist suspicious assets/domains.
