### ISSUE TITLE
Suspicious 10 domains.

### ISSUE THREAD

**Issue by quadrigaex** [Lobstrco/fraudulent-assets#90]
### Specific Domain(s)
milkywaystellar.com
jackpotstellar.com
thestellarfarm.com
Stellarflies.com
liquidstellars.com
Eastellar.com
mergetokens.com
Stellareast.com
uptownstellar.com
rivalcoins.io

### The reason why you think we need to blacklist these domains
SCAMMING ASSETS.

**Comment by CryptoHobbyist** [comment]
I've finished checking and adding these to my list, sadly it is now over 700 researched and found to be very questionable domains.

**Comment by star-dust-one** [comment]
Thank you. We added some of these domains to our blacklist.
