### ISSUE TITLE
Suspicious assets: SLT Smartlands token

### ISSUE THREAD

**Issue by Philter1972** [Lobstrco/fraudulent-assets#92]
I bought this asset and admin de-authorized my purchase. Now I cannot sell asset and my investment esentially taken. Thanks in advance for your time reviewing this issue.

### Specific asset code(s) and issuer(s)
https://stellar.expert/explorer/public/asset/SLT-GBY2LPKDJPLWXFL6P4QVE2JHWI6L2P74JKWAPWWOVIQFUDBP4AAZ27CV

### The reason why you think we need to blacklist these assets
How can an asset be de-authorized for no reason? How can I trust a system where assets purchased can be stolen for no reason with no recourse? Clawback was NOT enabled and Authorization flags are:
Issuer allows any Stellar account to add this asset.
Asset issuer can not freeze the asset in your Stellar account.
These options can be changed by asset issuer later.
I really don't understand why my purchase was deauthorized.

### Specific domain(s) of asset
https://smartlands.in/

### The source where suspicious assets are mentioned (e.g. Telegram/WhatsApp/Facebook links)
I did not see it mentioned anywhere just was searching domains / assets and thought the details sounded like a good investment...

### Evidence of fraud (e.g. screenshots, links with complaints, or any other proof)
![image](https://user-images.githubusercontent.com/68793327/176187685-7a935d46-8138-4dfb-af20-6b1d598b759a.png)
![image](https://user-images.githubusercontent.com/68793327/176188147-8fcf2728-e3ae-4c84-bf3b-96b7b2eff5df.png)
![image](https://user-images.githubusercontent.com/68793327/176188428-e66509fe-3a84-4425-b9dd-704fd805fd42.png)

**Comment by star-dust-one** [comment]
Thank you for this issue. You're right. We've added this domain to our blacklist.
