### ISSUE TITLE
Suspicious assets: XLMMATIC

### ISSUE THREAD

**Issue by CryptoCognos** [Lobstrco/fraudulent-assets#95]
### Specific asset code(s) and issuer(s)
asset XLMMATIC-GD46GYILIGKHDEGEN4UT2LBC6BQYFTBC3VXTJUXASMD7XRADMZZMQUNR
issuer GD46GYILIGKHDEGEN4UT2LBC6BQYFTBC3VXTJUXASMD7XRADMZZMQUNR

### The reason why you think we need to blacklist these assets
Yet another fake asset, no deposit withdraw, has about 2XLM on balance

### Specific domain(s) of asset
[xlmmatic.netlify.app](https://xlmmatic.netlify.app/)

**Comment by star-dust-one** [comment]
Thanks! Added to our blacklist
