### ISSUE TITLE
Suspicious issuer: GDE7C7VQNJUL7IL4WFFBZWWKH22JCQXMZC45LU75EZ7NZVH3MZ24JTMJ

### ISSUE THREAD

**Issue by CryptoCognos** [Lobstrco/fraudulent-assets#96]
### Specific asset code(s) and issuer(s)
issuer: GDE7C7VQNJUL7IL4WFFBZWWKH22JCQXMZC45LU75EZ7NZVH3MZ24JTMJ

### The reason why you think we need to blacklist these assets
Issuer issues some fake crypto

### Specific domain(s) of asset
Crafty use of redirecting domains to real projects like stellarflare.org -> flare.xyz
Although the "flare" project looks quite fake too.
( way more energy was wasted into write the pitch than into writing documentation )

**Comment by star-dust-one** [comment]
Thanks! Added this domain to the blacklist.
