### ISSUE TITLE
Suspicious assets: "CHEVRON"

### ISSUE THREAD

**Issue by stellarwatchdog** [Lobstrco/fraudulent-assets#97]
![BA45AE39-0124-456B-9135-AA1F9CDE97A0](https://user-images.githubusercontent.com/108224279/177407973-1c8d9a75-b73a-453b-81b6-46298c5e08d5.jpeg)

Fake asset 

### Specific asset code(s) and issuer(s)
CHEVRON GAKRSCYI36DT5R6C4CRB5EGAGBWR3VNFM57NKDUI7HDKMA7BLX5QQUSA
 
 CHEVRON
GAG64M3IO7DMWLCII64VTVVHH4IKBSEH665BJXCXJ64O6DPS5P5MNXTN

CHEVRON
GBCS7T7D4M25WJK4UC4P4S2TF4YFSKAJSKJN4UQOT4SMSDIJJKYCEUSA

### Specific domain(s) of asset
Stellarusa.org
Stellarpieces.com
Stellar-USA.org

**Comment by star-dust-one** [comment]
Thank you! All domains were added to our blacklist.
