### ISSUE TITLE
Fake Tokens: "Asset List and Domain”

### ISSUE THREAD

**Issue by stellarwatchdog** [Lobstrco/fraudulent-assets#98]
### Specific asset code(s) and issuer(s)
JPM  (Chase fake token)
GCPBVHEW6PPP5MAGF5TCQSFEKXBF2JMCQWG2SH6UXMTT7J2HLWNM3FAI

CHALICE (fake token)
GDRRPM6QPL2HOFNDF2DXXLTFFSHEFJY6EZQRXJ2MOJZK5F2CUDL2DGAL

eUSD (fake usd / Elon token)
GDO4VJVYFOPVM52UVRECBL4LKTMFQ7L4KDIQUPWMEOM4YFT62CEARELO

Atmosphere (Fake Token - no website)
GAC6LLQLUIGQMPTMXUF2WSLAE3X5HWIF66PLM2TSIIWSMS2Y45VSCXPW

MAERSK (Fake Token) forwarded 
GBYUNEJRGCFQ7UJKVDYB2SIT2XH2KHZPJKFNJALWOEQW6Z4ATJUNKXDZ

### The reason why you think we need to blacklist these assets

fake assets using copyrighted and trademarked logos and names of other companies. These companies have no interest in crypto and did not created these assets.

### Specific domain(s) of asset
Stellarusa.org
Galileominimg.fund (forwarded to another website) fake token.
elonstellar.co (fake Elon token)
atmosphere.stellarmint.io (Fake Token)
maerskcorn.digital (Fake Token - it’s forwarded to another website that’s not theirs)

**Comment by star-dust-one** [comment]
Thanks! We've added all domains to our blacklist.
